global:
  scrape_interval:     15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus' # Job to scrape Prometheus metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.8:9090']

  - job_name: 'service'
    metrics_path: '/actuator/prometheus' # Job to scrape application metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.8:8080']
        labels:
          application: 'First service'

  - job_name: 'second_service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.2.8:8082' ]
        labels:
          application: 'Second service'